<Project Sdk="Microsoft.NET.Sdk.Web">

    <Import Project="..\..\common.version.props"/>
    <Import Project="..\..\common.test.props"/>

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
        <RootNamespace>Hhs.EventManagerService</RootNamespace>
        <Title>TechSummus Hhs EventManager Service</Title>
        <Product>TechSummus Hhs EventManager Service</Product>
        <Description>TechSummus Hhs EventManager Service</Description>
        <Authors>TechSummus</Authors>
        <Copyright>2025</Copyright>
        <NoWarn>$(NoWarn);CS1591;CS1998;</NoWarn>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\..\..\shared\src\Hhs.Shared.Hosting.Microservices\Hhs.Shared.Hosting.Microservices.csproj" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\Hhs.EventManagerService.Application\Hhs.EventManagerService.Application.csproj"/>
        <ProjectReference Include="..\Hhs.EventManagerService.MongoDb\Hhs.EventManagerService.MongoDb.csproj"/>
    </ItemGroup>

    <ItemGroup>
        <Content Include="..\..\public_key.xml">
            <Link>public_key.xml</Link>
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </Content>
        <Content Include="..\..\.dockerignore">
            <Link>.dockerignore</Link>
        </Content>
    </ItemGroup>

    <ItemGroup>
        <Compile Remove="Logs\**"/>
        <Content Remove="Logs\**"/>
        <EmbeddedResource Remove="Logs\**"/>
        <None Remove="Logs\**"/>
    </ItemGroup>

</Project>