<Project Sdk="Microsoft.NET.Sdk">

    <Import Project="..\..\configureawait.props" />
    <Import Project="..\..\common.props" />

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <AssemblyName>HsnSoft.Base.Authorization.Abstractions</AssemblyName>
        <PackageId>HsnSoft.Base.Authorization.Abstractions</PackageId>
        <AssetTargetFallback>$(AssetTargetFallback);portable-net45+win8+wp8+wpa81;</AssetTargetFallback>
        <GenerateAssemblyConfigurationAttribute>false</GenerateAssemblyConfigurationAttribute>
        <GenerateAssemblyCompanyAttribute>false</GenerateAssemblyCompanyAttribute>
        <GenerateAssemblyProductAttribute>false</GenerateAssemblyProductAttribute>
        <RootNamespace />
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.AspNetCore.Authorization" Version="$(MicrosoftAspNetCorePackageVersion)" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\HsnSoft.Base.Localization.Abstractions\HsnSoft.Base.Localization.Abstractions.csproj" />
        <ProjectReference Include="..\HsnSoft.Base.MultiTenancy\HsnSoft.Base.MultiTenancy.csproj" />
    </ItemGroup>

</Project>