<Project Sdk="Microsoft.NET.Sdk">

    <Import Project="..\..\common.version.props" />
    <Import Project="..\..\common.test.props" />
    <Import Project="..\..\common.props" />

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <PackageId>Hhs.IdentityService.Domain</PackageId>
        <RootNamespace>Hhs.IdentityService.Domain</RootNamespace>
        <Title>TechSummus Hhs Identity Service Domain</Title>
        <Description>TechSummus Hhs Identity Service Domain</Description>
        <PackageTags>TechSummus Hhs Identity Service Domain</PackageTags>
    </PropertyGroup>
    
    <ItemGroup>
        <!--        <PackageReference Include="HsnSoft.Base.EntityFrameworkCore.PostgreSql" Version="$(HsnSoftFrameworkVersion)" />-->
        <ProjectReference Include="..\..\..\..\src\HsnSoft.Base.EntityFrameworkCore.PostgreSql\HsnSoft.Base.EntityFrameworkCore.PostgreSql.csproj" />
        <!--        <PackageReference Include="HsnSoft.Base.Ddd.Domain" Version="$(HsnSoftFrameworkVersion)" />-->
        <ProjectReference Include="..\..\..\..\src\HsnSoft.Base.Ddd.Domain\HsnSoft.Base.Ddd.Domain.csproj" />

    </ItemGroup>

    <ItemGroup>
<!--        <PackageReference Include="Hhs.Shared.Helper" Version="$(HhsSharedVersion)" />-->
        <ProjectReference Include="..\..\..\shared\src\Hhs.Shared.Helper\Hhs.Shared.Helper.csproj" />
    </ItemGroup>

    <ItemGroup>
        <EmbeddedResource Include="Localization\IdentityService\*.json" />
        <Content Remove="Localization\IdentityService\*.json" />
    </ItemGroup>

    <ItemGroup>
      <Compile Remove="AuthDomain\Entities\AppUserLogin.cs" />
    </ItemGroup>

</Project>
