<Project Sdk="Microsoft.NET.Sdk">

    <Import Project="..\..\common.version.props"/>
    <Import Project="..\..\common.props"/>

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <PackageId>Hhs.Shared.Localization</PackageId>
        <RootNamespace>Hhs.Shared.Localization</RootNamespace>
        <Title>TechSummus HHS Shared Localization</Title>
        <Description>TechSummus HHS Shared Localization</Description>
        <PackageTags>TechSummus HHS Shared Localization</PackageTags>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\..\..\src\HsnSoft.Base.Validation\HsnSoft.Base.Validation.csproj"/>
    </ItemGroup>

    <ItemGroup>
        <EmbeddedResource Include="Shared\*.json"/>
        <Content Remove="Shared\*.json"/>
    </ItemGroup>

</Project>