<Project Sdk="Microsoft.NET.Sdk">

    <Import Project="..\..\common.version.props"/>
    <Import Project="..\..\common.test.props"/>
    <Import Project="..\..\common.props"/>

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <PackageId>Hhs.AdministrationService.Application</PackageId>
        <RootNamespace>Hhs.AdministrationService.Application</RootNamespace>
        <Title>TechSummus Hhs Administration Service Application</Title>
        <Description>TechSummus Hhs Administration Service Application</Description>
        <PackageTags>TechSummus Hhs Administration Service Application</PackageTags>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\..\..\shared\src\Hhs.Shared.Contracts\Hhs.Shared.Contracts.csproj"/>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\Hhs.AdministrationService.Domain\Hhs.AdministrationService.Domain.csproj"/>
    </ItemGroup>

</Project>