// <auto-generated />
using System;
using Hhs.FeedRService.EntityFrameworkCore.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Hhs.FeedRService.EntityFrameworkCore.Migrations
{
    [DbContext(typeof(FeedRServiceDbContext))]
    [Migration("20260625020020_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Hhs.FeedRService.Domain.InfraDomain.Entities.PostgreSQL.EventInboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("CorrelationId")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("CreationTime");

                    b.Property<Guid?>("CreatorId")
                        .HasColumnType("uuid")
                        .HasColumnName("CreatorId");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("EventName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<DateTime>("LastModificationTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("LastModificationTime");

                    b.Property<Guid?>("LastModifierId")
                        .HasColumnType("uuid")
                        .HasColumnName("LastModifierId");

                    b.Property<string>("Payload")
                        .HasColumnType("jsonb");

                    b.Property<DateTime?>("ProcessedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("RetryCount")
                        .HasColumnType("integer");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("Status");

                    b.ToTable("EventInboxMessages", "public");
                });

            modelBuilder.Entity("Hhs.FeedRService.Domain.ReportingDomain.Entities.PostgreSQL.AdNetwork", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("CreationTime");

                    b.Property<Guid?>("CreatorId")
                        .HasColumnType("uuid")
                        .HasColumnName("CreatorId");

                    b.Property<string>("DisplayName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<DateTime>("LastModificationTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("LastModificationTime");

                    b.Property<Guid?>("LastModifierId")
                        .HasColumnType("uuid")
                        .HasColumnName("LastModifierId");

                    b.Property<string>("NetworkCode")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.HasKey("Id");

                    b.HasIndex("NetworkCode")
                        .IsUnique();

                    b.ToTable("AdNetworks", "public");
                });

            modelBuilder.Entity("Hhs.FeedRService.Domain.ReportingDomain.Entities.PostgreSQL.AdUnitClient", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("AdUnitCode")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<Guid>("AdUnitTopLevelId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ClientId")
                        .HasColumnType("uuid");

                    b.Property<string>("ClientName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("CreationTime");

                    b.Property<Guid?>("CreatorId")
                        .HasColumnType("uuid")
                        .HasColumnName("CreatorId");

                    b.Property<DateTime>("LastModificationTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("LastModificationTime");

                    b.Property<Guid?>("LastModifierId")
                        .HasColumnType("uuid")
                        .HasColumnName("LastModifierId");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("TenantId");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.HasIndex("TenantId");

                    b.HasIndex("AdUnitTopLevelId", "AdUnitCode")
                        .IsUnique();

                    b.ToTable("AdUnitClients", "public");
                });

            modelBuilder.Entity("Hhs.FeedRService.Domain.ReportingDomain.Entities.PostgreSQL.AdUnitTopLevel", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("AdNetworkId")
                        .HasColumnType("uuid");

                    b.Property<string>("AdUnitTopLevelCode")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("CreationTime");

                    b.Property<Guid?>("CreatorId")
                        .HasColumnType("uuid")
                        .HasColumnName("CreatorId");

                    b.Property<DateTime>("LastModificationTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("LastModificationTime");

                    b.Property<Guid?>("LastModifierId")
                        .HasColumnType("uuid")
                        .HasColumnName("LastModifierId");

                    b.HasKey("Id");

                    b.HasIndex("AdUnitTopLevelCode");

                    b.HasIndex("AdNetworkId", "AdUnitTopLevelCode")
                        .IsUnique();

                    b.ToTable("AdUnitTopLevels", "public");
                });

            modelBuilder.Entity("Hhs.FeedRService.Domain.ReportingDomain.Entities.PostgreSQL.DashboardResponse", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<long>("ActiveViewEligibleImpressions")
                        .HasColumnType("bigint");

                    b.Property<Guid>("AdUnitClientId")
                        .HasColumnType("uuid");

                    b.Property<double>("AverageEcpm")
                        .HasColumnType("double precision");

                    b.Property<Guid>("ClientId")
                        .HasColumnType("uuid");

                    b.Property<long>("CodeServedCount")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("CreationTime");

                    b.Property<Guid?>("CreatorId")
                        .HasColumnType("uuid")
                        .HasColumnName("CreatorId");

                    b.Property<string>("DemandChannel")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("DemandSubchannelName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<long>("Impressions")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("LastModificationTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("LastModificationTime");

                    b.Property<Guid?>("LastModifierId")
                        .HasColumnType("uuid")
                        .HasColumnName("LastModifierId");

                    b.Property<string>("OrderId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("OrderName")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<DateTime>("ReportDate")
                        .HasColumnType("date");

                    b.Property<double>("Revenue")
                        .HasColumnType("double precision");

                    b.Property<Guid>("SourceMongoDbId")
                        .HasColumnType("uuid");

                    b.Property<int>("SourceRowCount")
                        .HasColumnType("integer");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("TenantId");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.HasIndex("ReportDate");

                    b.HasIndex("TenantId");

                    b.HasIndex("ClientId", "ReportDate");

                    b.HasIndex("AdUnitClientId", "ReportDate", "DemandChannel", "DemandSubchannelName", "OrderId")
                        .IsUnique();

                    b.ToTable("DashboardResponses", "public");
                });

            modelBuilder.Entity("Hhs.FeedRService.Domain.ReportingDomain.Entities.PostgreSQL.MongoToPostgresMapping", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("CreationTime");

                    b.Property<Guid?>("CreatorId")
                        .HasColumnType("uuid")
                        .HasColumnName("CreatorId");

                    b.Property<DateTime>("DerivationDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DerivationStatus")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<int>("DerivedRecordCount")
                        .HasColumnType("integer");

                    b.Property<string>("DerivedRecordIds")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<DateTime>("LastModificationTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("LastModificationTime");

                    b.Property<Guid?>("LastModifierId")
                        .HasColumnType("uuid")
                        .HasColumnName("LastModifierId");

                    b.Property<Guid>("MongoDbDocumentId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("DerivationStatus");

                    b.HasIndex("MongoDbDocumentId")
                        .IsUnique();

                    b.ToTable("MongoToPostgresMappings", "public");
                });

            modelBuilder.Entity("Hhs.FeedRService.Domain.ReportingDomain.Entities.PostgreSQL.AdUnitClient", b =>
                {
                    b.HasOne("Hhs.FeedRService.Domain.ReportingDomain.Entities.PostgreSQL.AdUnitTopLevel", "AdUnitTopLevel")
                        .WithMany("Clients")
                        .HasForeignKey("AdUnitTopLevelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AdUnitTopLevel");
                });

            modelBuilder.Entity("Hhs.FeedRService.Domain.ReportingDomain.Entities.PostgreSQL.AdUnitTopLevel", b =>
                {
                    b.HasOne("Hhs.FeedRService.Domain.ReportingDomain.Entities.PostgreSQL.AdNetwork", "AdNetwork")
                        .WithMany("TopLevelAdUnits")
                        .HasForeignKey("AdNetworkId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AdNetwork");
                });

            modelBuilder.Entity("Hhs.FeedRService.Domain.ReportingDomain.Entities.PostgreSQL.DashboardResponse", b =>
                {
                    b.HasOne("Hhs.FeedRService.Domain.ReportingDomain.Entities.PostgreSQL.AdUnitClient", "AdUnitClient")
                        .WithMany("DailyReports")
                        .HasForeignKey("AdUnitClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AdUnitClient");
                });

            modelBuilder.Entity("Hhs.FeedRService.Domain.ReportingDomain.Entities.PostgreSQL.AdNetwork", b =>
                {
                    b.Navigation("TopLevelAdUnits");
                });

            modelBuilder.Entity("Hhs.FeedRService.Domain.ReportingDomain.Entities.PostgreSQL.AdUnitClient", b =>
                {
                    b.Navigation("DailyReports");
                });

            modelBuilder.Entity("Hhs.FeedRService.Domain.ReportingDomain.Entities.PostgreSQL.AdUnitTopLevel", b =>
                {
                    b.Navigation("Clients");
                });
#pragma warning restore 612, 618
        }
    }
}
