namespace Hhs.ContentService.Domain.ContentDomain.Consts.Facilities;

public static class CustomerContentOperationFacilities
{
    public const string CUSTOMER_CONTENT_CREATED = "CUSTOMER_CONTENT_CREATED";
    public const string CUSTOMER_CONTENT_NORMALIZED_SUCCESS = "CUSTOMER_CONTENT_NORMALIZED_SUCCESS";
    public const string CUSTOMER_CONTENT_VIDEO_GENERATION_APPROVED = "CUSTOMER_CONTENT_VIDEO_GENERATION_APPROVED";

    public const string CUSTOMER_CONTENT_NORMALIZED_FAIL = "CUSTOMER_CONTENT_NORMALIZED_FAIL";
    public const string CUSTOMER_CONTENT_VIDEO_GENERATION_FAIL = "CUSTOMER_CONTENT_VIDEO_GENERATION_FAIL";
    public const string CUSTOMER_CONTENT_STATUS_FAIL = "CUSTOMER_CONTENT_STATUS_FAIL";

    public const string CUSTOMER_CONTENT_VIDEO_GENERATION_SKIPPED_OLD_CONTENT = "CUSTOMER_CONTENT_VIDEO_GENERATION_SKIPPED_OLD_CONTENT";
    public const string CUSTOMER_CONTENT_VIDEO_GENERATION_SKIPPED_EARLY_TIME = "CUSTOMER_CONTENT_VIDEO_GENERATION_SKIPPED_EARLY_TIME";
    public const string CUSTOMER_CONTENT_VIDEO_GENERATION_SKIPPED_DAILY_LIMIT = "CUSTOMER_CONTENT_VIDEO_GENERATION_SKIPPED_DAILY_LIMIT";
    public const string CUSTOMER_CONTENT_VIDEO_GENERATION_SKIPPED_REGENERATION_FAILED = "CUSTOMER_CONTENT_VIDEO_GENERATION_SKIPPED_REGENERATION_FAILED";

    public const string CUSTOMER_CONTENT_VIDEO_GENERATION_SUCCESS = "CUSTOMER_CONTENT_VIDEO_GENERATION_SUCCESS";

    public const string ADS_STARTED = "STARTED";
    public const string ADS_ERROR = "ERROR";
    public const string ADS_TIMEOUT = "TIMEOUT";
    public const string ADS_EMPTY = "EMPTY";
}