// <auto-generated />
using System;
using Hhs.ContentService.EntityFrameworkCore.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Hhs.ContentService.EntityFrameworkCore.Migrations
{
    [DbContext(typeof(ContentServiceDbContext))]
    [Migration("20260612184222_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Hhs.ContentService.Domain.ContentDomain.Entities.AnalysisContent", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("AnalysisDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CorrelationId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("CreationTime");

                    b.Property<Guid?>("CreatorId")
                        .HasColumnType("uuid")
                        .HasColumnName("CreatorId");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("IsDeleted");

                    b.Property<DateTime>("LastModificationTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("LastModificationTime");

                    b.Property<Guid?>("LastModifierId")
                        .HasColumnType("uuid")
                        .HasColumnName("LastModifierId");

                    b.Property<Guid?>("NormalizedRequestId")
                        .HasColumnType("uuid");

                    b.Property<int>("OperationStatus")
                        .HasColumnType("integer");

                    b.Property<string>("OperationStatusDescription")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.Property<string>("ScopeKey")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("StorageVideoUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.Property<Guid?>("VideoRequestId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("AnalysisDate");

                    b.HasIndex("OperationStatus");

                    b.HasIndex("ScopeKey");

                    b.ToTable("AnalysisContents", (string)null);
                });

            modelBuilder.Entity("Hhs.ContentService.Domain.ContentDomain.Entities.ContentVideoGenerationLimit", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("ContentReferenceIds")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<Guid?>("CustomerVpSettingId")
                        .HasColumnType("uuid");

                    b.Property<string>("ScopeKey")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<DateTime>("VideoGenerationDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("VideoGenerationType")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CustomerVpSettingId");

                    b.HasIndex("ScopeKey", "VideoGenerationType");

                    b.ToTable("ContentVideoGenerationLimits", (string)null);
                });

            modelBuilder.Entity("Hhs.ContentService.Domain.ContentDomain.Entities.CustomerContent", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("CorrelationId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("CreationTime");

                    b.Property<Guid?>("CreatorId")
                        .HasColumnType("uuid")
                        .HasColumnName("CreatorId");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("IsDeleted");

                    b.Property<DateTime>("LastModificationTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("LastModificationTime");

                    b.Property<Guid?>("LastModifierId")
                        .HasColumnType("uuid")
                        .HasColumnName("LastModifierId");

                    b.Property<Guid?>("NormalizedRequestId")
                        .HasColumnType("uuid");

                    b.Property<int>("OperationStatus")
                        .HasColumnType("integer");

                    b.Property<string>("OperationStatusDescription")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.Property<DateTime?>("ReleaseTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ScopeKey")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("SlugKey")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<string>("StorageVideoUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.Property<Guid?>("VideoRequestId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("OperationStatus");

                    b.HasIndex("ScopeKey", "SlugKey", "IsDeleted")
                        .IsUnique();

                    b.ToTable("CustomerContents", (string)null);
                });

            modelBuilder.Entity("Hhs.ContentService.Domain.ContentDomain.Entities.CustomerContentVisit", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CustomerContentId")
                        .HasColumnType("uuid");

                    b.Property<string>("ScopeKey")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("VisitResponse")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<DateTime>("VisitTime")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CustomerContentId");

                    b.HasIndex("ScopeKey");

                    b.HasIndex("VisitResponse");

                    b.HasIndex("VisitTime");

                    b.ToTable("CustomerContentVisits", (string)null);
                });

            modelBuilder.Entity("Hhs.ContentService.Domain.SettingDomain.Entities.CustomerVpSetting", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("CreationTime");

                    b.Property<Guid?>("CreatorId")
                        .HasColumnType("uuid")
                        .HasColumnName("CreatorId");

                    b.Property<int>("DailyAnalysisVideoGenerationLimit")
                        .HasColumnType("integer");

                    b.Property<int>("DailyAnalysisVideoGenerationStartedUtcHour")
                        .HasColumnType("integer");

                    b.Property<int>("DailyDirectVideoGenerationLimit")
                        .HasColumnType("integer");

                    b.Property<int>("DailyDirectVideoGenerationStartedUtcHour")
                        .HasColumnType("integer");

                    b.Property<int>("DailyTrendVideoGenerationLimit")
                        .HasColumnType("integer");

                    b.Property<int>("DailyTrendVideoGenerationStartedUtcHour")
                        .HasColumnType("integer");

                    b.Property<int>("DailyTrendVideoMinVisitCount")
                        .HasColumnType("integer");

                    b.Property<int>("DailyTrendVideoWaitStatisticHour")
                        .HasColumnType("integer");

                    b.Property<string>("DomainName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("ExcludePathFilters")
                        .HasColumnType("jsonb");

                    b.Property<string>("IncludePathFilters")
                        .HasColumnType("jsonb");

                    b.Property<bool>("IsBlocked")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("IsDeleted");

                    b.Property<DateTime>("LastModificationTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("LastModificationTime");

                    b.Property<Guid?>("LastModifierId")
                        .HasColumnType("uuid")
                        .HasColumnName("LastModifierId");

                    b.Property<string>("ScopeKey")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.HasKey("Id");

                    b.HasIndex("DomainName")
                        .IsUnique();

                    b.HasIndex("ScopeKey")
                        .IsUnique();

                    b.ToTable("CustomerVpSettings", (string)null);
                });

            modelBuilder.Entity("Hhs.ContentService.Domain.ContentDomain.Entities.ContentVideoGenerationLimit", b =>
                {
                    b.HasOne("Hhs.ContentService.Domain.SettingDomain.Entities.CustomerVpSetting", null)
                        .WithMany("VideoGenerationHistories")
                        .HasForeignKey("CustomerVpSettingId");
                });

            modelBuilder.Entity("Hhs.ContentService.Domain.SettingDomain.Entities.CustomerVpSetting", b =>
                {
                    b.Navigation("VideoGenerationHistories");
                });
#pragma warning restore 612, 618
        }
    }
}
