// <auto-generated />
using System;
using Hhs.AdministrationService.EntityFrameworkCore.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Hhs.AdministrationService.EntityFrameworkCore.Migrations
{
    [DbContext(typeof(AdministrationServiceDbContext))]
    partial class AdministrationServiceDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Hhs.AdministrationService.Domain.MenuDomain.Entities.AppMenu", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<int>("ChannelType")
                        .HasColumnType("integer");

                    b.Property<int>("DockType")
                        .HasColumnType("integer");

                    b.Property<string>("Icon")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("NodeType")
                        .HasColumnType("integer");

                    b.Property<Guid?>("ParentId")
                        .HasColumnType("uuid");

                    b.Property<string>("Route")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("UniqueCode")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("ParentId");

                    b.HasIndex("UniqueCode")
                        .IsUnique();

                    b.ToTable("AppMenus", (string)null);
                });

            modelBuilder.Entity("Hhs.AdministrationService.Domain.MenuDomain.Entities.AppMenuPermission", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("AppMenuId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("PermissionId")
                        .HasColumnType("uuid");

                    b.Property<int>("RelationType")
                        .HasColumnType("integer");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("PermissionId");

                    b.HasIndex("AppMenuId", "PermissionId")
                        .IsUnique();

                    b.ToTable("AppMenuPermissions", (string)null);
                });

            modelBuilder.Entity("Hhs.AdministrationService.Domain.PermissionDomain.Entities.AppRolePermission", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("AppRoleId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("PermissionId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("PermissionId");

                    b.HasIndex("AppRoleId", "PermissionId")
                        .IsUnique();

                    b.ToTable("AppRolePermissions", (string)null);
                });

            modelBuilder.Entity("Hhs.AdministrationService.Domain.PermissionDomain.Entities.AppRolePermissionConstraint", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("AppRoleId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("PermissionId")
                        .HasColumnType("uuid");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.HasKey("Id");

                    b.HasIndex("PermissionId");

                    b.HasIndex("AppRoleId", "PermissionId")
                        .IsUnique();

                    b.ToTable("AppRolePermissionConstraints", (string)null);
                });

            modelBuilder.Entity("Hhs.AdministrationService.Domain.PermissionDomain.Entities.OldMenuMap", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("ClientId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ClientMenuType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Hierarchy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Icon")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("MapType")
                        .HasColumnType("integer");

                    b.Property<bool>("OnlyAccessSystemUsers")
                        .HasColumnType("boolean");

                    b.Property<byte>("OrderNo")
                        .HasColumnType("smallint");

                    b.Property<string>("ParentUniqueName")
                        .HasColumnType("text");

                    b.Property<string>("UniqueName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("OldMenuMaps", (string)null);
                });

            modelBuilder.Entity("Hhs.AdministrationService.Domain.PermissionDomain.Entities.OldMenuPermissionMap", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("ClientId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LeafMenuUniqueName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<byte>("OrderNo")
                        .HasColumnType("smallint");

                    b.Property<int>("PermissionType")
                        .HasColumnType("integer");

                    b.Property<string>("PermissionUniqueName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("OldMenuPermissionMaps", (string)null);
                });

            modelBuilder.Entity("Hhs.AdministrationService.Domain.PermissionDomain.Entities.Permission", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("Name")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<int>("PermissionType")
                        .HasColumnType("integer");

                    b.Property<string>("UniqueCode")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.HasKey("Id");

                    b.HasIndex("UniqueCode")
                        .IsUnique();

                    b.ToTable("Permissions", (string)null);
                });

            modelBuilder.Entity("Hhs.AdministrationService.Domain.PermissionDomain.Entities.PermissionDependency", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("DependsOnPermissionId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("PermissionId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("DependsOnPermissionId");

                    b.HasIndex("PermissionId", "DependsOnPermissionId")
                        .IsUnique();

                    b.ToTable("PermissionDependencies", (string)null);
                });

            modelBuilder.Entity("Hhs.AdministrationService.Domain.PermissionDomain.Entities.PermissionGrant", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("Name");

                    b.Property<string>("ProviderKey")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("ProviderKey");

                    b.Property<string>("ProviderName")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("ProviderName");

                    b.HasKey("Id");

                    b.HasIndex("Name", "ProviderName", "ProviderKey")
                        .IsUnique();

                    b.ToTable("PermissionGrants", (string)null);
                });

            modelBuilder.Entity("Hhs.Shared.EventInbox.Entities.EventInboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("CorrelationId")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("CreationTime");

                    b.Property<Guid?>("CreatorId")
                        .HasColumnType("uuid")
                        .HasColumnName("CreatorId");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("EventName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<DateTime>("LastModificationTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("LastModificationTime");

                    b.Property<Guid?>("LastModifierId")
                        .HasColumnType("uuid")
                        .HasColumnName("LastModifierId");

                    b.Property<string>("Payload")
                        .HasColumnType("jsonb");

                    b.Property<DateTime?>("ProcessedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("RetryCount")
                        .HasColumnType("integer");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("Status");

                    b.ToTable("EventInboxMessages", (string)null);
                });

            modelBuilder.Entity("Hhs.AdministrationService.Domain.MenuDomain.Entities.AppMenu", b =>
                {
                    b.HasOne("Hhs.AdministrationService.Domain.MenuDomain.Entities.AppMenu", "Parent")
                        .WithMany("Nodes")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("Hhs.AdministrationService.Domain.MenuDomain.Entities.AppMenuPermission", b =>
                {
                    b.HasOne("Hhs.AdministrationService.Domain.MenuDomain.Entities.AppMenu", "AppMenu")
                        .WithMany("MenuPermissions")
                        .HasForeignKey("AppMenuId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Hhs.AdministrationService.Domain.PermissionDomain.Entities.Permission", "Permission")
                        .WithMany()
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AppMenu");

                    b.Navigation("Permission");
                });

            modelBuilder.Entity("Hhs.AdministrationService.Domain.PermissionDomain.Entities.AppRolePermission", b =>
                {
                    b.HasOne("Hhs.AdministrationService.Domain.PermissionDomain.Entities.Permission", "Permission")
                        .WithMany()
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Permission");
                });

            modelBuilder.Entity("Hhs.AdministrationService.Domain.PermissionDomain.Entities.AppRolePermissionConstraint", b =>
                {
                    b.HasOne("Hhs.AdministrationService.Domain.PermissionDomain.Entities.Permission", "Permission")
                        .WithMany()
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Permission");
                });

            modelBuilder.Entity("Hhs.AdministrationService.Domain.PermissionDomain.Entities.PermissionDependency", b =>
                {
                    b.HasOne("Hhs.AdministrationService.Domain.PermissionDomain.Entities.Permission", "DependsOnPermission")
                        .WithMany("ChildPermissions")
                        .HasForeignKey("DependsOnPermissionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Hhs.AdministrationService.Domain.PermissionDomain.Entities.Permission", "Permission")
                        .WithMany("ParentPermissions")
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("DependsOnPermission");

                    b.Navigation("Permission");
                });

            modelBuilder.Entity("Hhs.AdministrationService.Domain.MenuDomain.Entities.AppMenu", b =>
                {
                    b.Navigation("MenuPermissions");

                    b.Navigation("Nodes");
                });

            modelBuilder.Entity("Hhs.AdministrationService.Domain.PermissionDomain.Entities.Permission", b =>
                {
                    b.Navigation("ChildPermissions");

                    b.Navigation("ParentPermissions");
                });
#pragma warning restore 612, 618
        }
    }
}
