<Project Sdk="Microsoft.NET.Sdk.Worker">

    <Import Project="..\..\common.version.props"/>

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
        <RootNamespace>Hhs.Scheduler.ApiTrigger.Host</RootNamespace>
        <Title>TechSummus Hhs Scheduler Api Trigger</Title>
        <Product>TechSummus Hhs Scheduler Api Trigger</Product>
        <Description>TechSummus Hhs Scheduler Api Trigger</Description>
        <Authors>TechSummus</Authors>
        <Copyright>2025</Copyright>
        <NoWarn>$(NoWarn);CS1591;CS1998;</NoWarn>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Quartz" Version="3.18.1"/>
        <PackageReference Include="Quartz.Extensions.Hosting" Version="3.18.1"/>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\..\..\..\src\HsnSoft.Base.AspNetCore\HsnSoft.Base.AspNetCore.csproj" />
    </ItemGroup>

    <ItemGroup>
        <Content Include="..\..\.dockerignore">
            <Link>.dockerignore</Link>
        </Content>
    </ItemGroup>

    <ItemGroup>
        <Content Update="scheduler.json">
            <CopyToOutputDirectory>Always</CopyToOutputDirectory>
        </Content>
    </ItemGroup>

    <ItemGroup>
        <Compile Remove="Logs\**"/>
        <Content Remove="Logs\**"/>
        <EmbeddedResource Remove="Logs\**"/>
        <None Remove="Logs\**"/>
    </ItemGroup>

</Project>
