<Project>
    <PropertyGroup>
        <LangVersion>latest</LangVersion>
        <Version>2026.1</Version>
        <HsnSoftFrameworkVersion>2026.10.30</HsnSoftFrameworkVersion>
        <MicrosoftAspNetCorePackageVersion>10.0.7</MicrosoftAspNetCorePackageVersion>
        <MicrosoftEntityFrameworkCorePackageVersion>10.0.7</MicrosoftEntityFrameworkCorePackageVersion>
    </PropertyGroup>
</Project>