<Project>
    <PropertyGroup>
        <LangVersion>latest</LangVersion>
        <Version>2026.1</Version>
        <HsnSoftFrameworkVersion>2026.10.31</HsnSoftFrameworkVersion>
        <MicrosoftAspNetCorePackageVersion>10.0.5</MicrosoftAspNetCorePackageVersion>
        <MicrosoftEntityFrameworkCorePackageVersion>10.0.5</MicrosoftEntityFrameworkCorePackageVersion>
    </PropertyGroup>
</Project>