namespace Hhs.ContentService.Domain.ContentDomain.Consts.Facilities;

public static class AnalysisContentOperationFacilities
{
    public const string ANALYSIS_CONTENT_CREATED = " ANALYSIS_CONTENT_CREATED";
    public const string ANALYSIS_CONTENT_NORMALIZED_SUCCESS = " ANALYSIS_CONTENT_NORMALIZED_SUCCESS";

    public const string ANALYSIS_CONTENT_NORMALIZED_FAIL = " ANALYSIS_CONTENT_NORMALIZED_FAIL";
    public const string ANALYSIS_CONTENT_VIDEO_GENERATION_FAIL = " ANALYSIS_CONTENT_VIDEO_GENERATION_FAIL";
    public const string ANALYSIS_CONTENT_STATUS_FAIL = " ANALYSIS_CONTENT_STATUS_FAIL";

    public const string ANALYSIS_CONTENT_VIDEO_GENERATION_SUCCESS = " ANALYSIS_CONTENT_VIDEO_GENERATION_SUCCESS";
}