name: 'Publish BaGet Server'

on:
  workflow_dispatch:
  push:
    branches: [ "DEVELOPMENT" ]

jobs:
  build:
    name: 'BaGet Server Publish JOB'
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of analysis

      - name: Get Version
        uses: kzrnm/get-net-sdk-project-versions-action@v1
        id: get-version
        with:
          proj-path: ./common.version.props

      - name: Build & Publish
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          secrets: |
            "NUGET_SOURCE=https://baget.techsummus.com/v3/index.json"
            "NUGET_SECRET=${{ secrets.REPO_BAGET_USER_SECRET }}"
            "VERSION_NUMBER=${{ steps.get-version.outputs.version }}"
            "ACTION_NUMBER=${{ github.run_number }}"
