<Project Sdk="Microsoft.NET.Sdk">

    <Import Project="..\..\common.version.props"/>
    <Import Project="..\..\common.test.props"/>
    <Import Project="..\..\common.props"/>

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <PackageId>Hhs.EventManagerService.Domain</PackageId>
        <RootNamespace>Hhs.EventManagerService.Domain</RootNamespace>
        <Title>TechSummus Hhs EventManager Service Domain</Title>
        <Description>TechSummus Hhs EventManager Service Domain</Description>
        <PackageTags>TechSummus Hhs EventManager Service Domain</PackageTags>
    </PropertyGroup>
    
    <ItemGroup>
        <ProjectReference Include="..\..\..\..\..\src\HsnSoft.Base.MongoDB\HsnSoft.Base.MongoDB.csproj" />
        <ProjectReference Include="..\..\..\..\..\src\HsnSoft.Base.Ddd.Domain\HsnSoft.Base.Ddd.Domain.csproj" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\..\..\shared\src\Hhs.Shared.Helper\Hhs.Shared.Helper.csproj" />
    </ItemGroup>

    <ItemGroup>
        <EmbeddedResource Include="Localization\EventManagerService\*.json"/>
        <Content Remove="Localization\EventManagerService\*.json"/>
    </ItemGroup>

</Project>
