<Project>

    <ItemGroup>
        <SonarQubeSetting Include="sonar.coverage.exclusions">
            <Value>
                **\Migrations\**,
                Models\Temp\**,
                **\Program*.cs,
                **\*Startup.cs
            </Value>
        </SonarQubeSetting>
        <SonarQubeSetting Include="sonar.exclusions">
            <Value>
                **\Migrations\**,
                **\Program*.cs
            </Value>
        </SonarQubeSetting>
    </ItemGroup>
    
</Project>