apiVersion: v1
kind: Namespace
metadata:
  name: ns-hhs-prod-apps

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hhs-app-scheduler-deployment
  namespace: ns-hhs-prod-apps
spec:
  replicas: 1 # SCHEDULER MUST BE 1 REPLICA
  revisionHistoryLimit: 2 # for roll-back, default to 10 if not specified
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 50%
  selector:
    matchLabels:
      app: hhs-app-scheduler
  template:
    metadata:
      labels:
        app: hhs-app-scheduler
    spec:
      terminationGracePeriodSeconds: 10 # successfully wait termination
      securityContext:
        fsGroupChangePolicy: Always
        fsGroup: 1001
      nodeSelector:
        kubernetes.io/os: linux
      tolerations:
        - key: "kubernetes.azure.com/scalesetpriority"
          operator: "Equal"
          value: "spot"
          effect: "NoSchedule"
        - key: "pool"
          operator: "Equal"
          value: "application"
          effect: "NoSchedule"
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: agentpool
                    operator: In
                    values:
                      - appspool  # Node pool select
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchLabels:
                    app: hhs-app-scheduler
                topologyKey: kubernetes.io/hostname
      containers:
        - name: hhs-app-scheduler-container
          image: ${IMAGE_NAME}:${BUILD_ID}
          imagePullPolicy: Always
          resources:
            requests:
              cpu: 25m
              memory: 64Mi
            limits:
              cpu: 50m
              memory: 128Mi
          env:
            - name: BUILD_NUMBER
              value: "${BUILD_ID}"
            - name: TZ
              value: "UTC"
            - name: ASPNETCORE_ENVIRONMENT
              value: "${ASPNETCORE_ENVIRONMENT}"
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: ASPNETCORE_URLS
              value: "http://+:8080"
          ports:
            - name: http-web-app
              containerPort: 8080
              protocol: TCP
          securityContext:
            runAsUser: 1001
            runAsGroup: 1001
            runAsNonRoot: true
            privileged: false
            readOnlyRootFilesystem: true
            allowPrivilegeEscalation: false
            capabilities:
              drop: [ "ALL" ]
            seccompProfile:
              type: "RuntimeDefault"
          startupProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 20
            periodSeconds: 40
            failureThreshold: 3
            successThreshold: 1
            timeoutSeconds: 5
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 0
            periodSeconds: 30
            failureThreshold: 3
            successThreshold: 1
            timeoutSeconds: 5
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 0
            periodSeconds: 10
            failureThreshold: 3
            successThreshold: 1
            timeoutSeconds: 5
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: hhs-app-scheduler-pdb
  namespace: ns-hhs-prod-apps
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: hhs-app-scheduler
---
# https://kubernetes.io/docs/concepts/services-networking/service/#defining-a-service
kind: Service
apiVersion: v1
metadata:
  name: hhs-app-scheduler-svc
  namespace: ns-hhs-prod-apps
spec:
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 80 # ServicePort
      targetPort: 8080 # ContainerPort
  selector:
    app: hhs-app-scheduler
