services:
  
  hhs-service-feedr-admanager-local:
    build:
      context: ../
      dockerfile: src/Hhs.FeedRService.AdManager.Http.Host/Dockerfile
      args:
        NUGET_USER: ${NUGET_USER}
        NUGET_TOKEN: ${NUGET_TOKEN}
    container_name: hhs-service-feedr-admanager-local-container
    image: hhs-service-feedr-admanager-local:1.0.0
    restart: always
    stop_grace_period: 20s # wait graceful termination
    ulimits:
      memlock:
        soft: -1
        hard: -1
    mem_limit: 1g
    security_opt:
      - no-new-privileges:true
    read_only: true
    tmpfs:
      # tmpfs-folder
      - /tmp
    labels:
      - "autoheal=true"
    healthcheck:
      #test: ["CMD", "curl", "--silent", "-f", "http://127.0.0.1:9000/api"]
      test: curl --fail http://localhost:8080/ReadinessCheck || exit 1
      start_period: 20s
      interval: 30s # application healthcheck period with "curl --fail"
      timeout: 5s # application healthcheck response timeout.
      retries: 3 # If the application does not respond after 3 attempts, it will be marked as "unhealthy".
    ports:
      - "7490:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=docker
      - BUILD_NUMBER=1
    networks:
      - infra-network

  hhs-service-feedr-weather-local:
    build:
      context: ../
      dockerfile: src/Hhs.FeedRService.Weather.Http.Host/Dockerfile
      args:
        NUGET_USER: ${NUGET_USER}
        NUGET_TOKEN: ${NUGET_TOKEN}
    container_name: hhs-service-feedr-weather-local-container
    image: hhs-service-feedr-weather-local:1.0.0
    restart: always
    stop_grace_period: 20s # wait graceful termination
    ulimits:
      memlock:
        soft: -1
        hard: -1
    mem_limit: 1g
    security_opt:
      - no-new-privileges:true
    read_only: true
    tmpfs:
      # tmpfs-folder
      - /tmp
    labels:
      - "autoheal=true"
    healthcheck:
      #test: ["CMD", "curl", "--silent", "-f", "http://127.0.0.1:9000/api"]
      test: curl --fail http://localhost:8080/ReadinessCheck || exit 1
      start_period: 20s
      interval: 30s # application healthcheck period with "curl --fail"
      timeout: 5s # application healthcheck response timeout.
      retries: 3 # If the application does not respond after 3 attempts, it will be marked as "unhealthy".
    ports:
      - "7492:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=docker
      - BUILD_NUMBER=1
    networks:
      - infra-network

  # check healthy status and restart
  autoheal:
    image: willfarrell/autoheal:latest
    tty: true
    restart: always
    environment:
      - AUTOHEAL_START_PERIOD=120 # wait 120 seconds for the initialization of all applications.
      - AUTOHEAL_INTERVAL=20 # auto-heal check period - check the health status of all applications.
      - AUTOHEAL_DEFAULT_STOP_TIMEOUT=10 # wait 10 seconds for the application to graceful shutdown.
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

networks:
  infra-network:
    name: local.infrastructure-network
    external: true