<Project>
    <PropertyGroup>
        <LangVersion>latest</LangVersion>
        <Version>2025.10</Version>
        <HhsIdentityVersion>2025.10.63</HhsIdentityVersion>
        <HhsSharedVersion>2026.1.67</HhsSharedVersion>
        <HsnSoftFrameworkVersion>2026.10.30</HsnSoftFrameworkVersion>
        <MicrosoftAspNetCorePackageVersion>10.0.7</MicrosoftAspNetCorePackageVersion>
        <MicrosoftEntityFrameworkCorePackageVersion>10.0.7</MicrosoftEntityFrameworkCorePackageVersion>
    </PropertyGroup>
</Project>