<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <IsPackable>false</IsPackable>
        <RootNamespace>Hhs.FeedRService.Test.Shared</RootNamespace>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="FluentAssertions" Version="8.10.0" />
        <PackageReference Include="Google.Ads.AdManager.V1" Version="1.0.0-beta03" />
        <PackageReference Include="Google.Dfp" Version="24.35.0" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\src\Hhs.FeedRService.AdManager.Http.Host\Hhs.FeedRService.AdManager.Http.Host.csproj" />
        <ProjectReference Include="..\..\src\Hhs.FeedRService.Weather.Http.Host\Hhs.FeedRService.Weather.Http.Host.csproj" />
    </ItemGroup>

</Project>
