<Project>
    <PropertyGroup>
        <LangVersion>latest</LangVersion>
        <Version>2025.10</Version>
        <HhsSharedVersion>2026.1.70</HhsSharedVersion>
        <HsnSoftFrameworkVersion>2026.10.31</HsnSoftFrameworkVersion>
        <MicrosoftAspNetCorePackageVersion>10.0.5</MicrosoftAspNetCorePackageVersion>
        <MicrosoftEntityFrameworkCorePackageVersion>10.0.5</MicrosoftEntityFrameworkCorePackageVersion>
    </PropertyGroup>
</Project>