namespace Hhs.TextNormalizerService.Domain.ContentDomain.Consts.Facilities;

public static class AnalysisNormalizedRequestOperationFacilities
{
    public const string ANALYSIS_NORMALIZED_REQUEST_CREATED = "ANALYSIS_NORMALIZED_REQUEST_CREATED";
    public const string ANALYSIS_NORMALIZED_REQUEST_OUTLINE_SUCCESS = "ANALYSIS_NORMALIZED_REQUEST_OUTLINE_SUCCESS";
    public const string ANALYSIS_NORMALIZED_REQUEST_OUTLINE_FAIL = "ANALYSIS_NORMALIZED_REQUEST_OUTLINE_FAIL";

    public const string ANALYSIS_NORMALIZED_REQUEST_STATUS_FAIL = "ANALYSIS_NORMALIZED_REQUEST_STATUS_FAIL";

    public const string ANALYSIS_CONTENT_VIDEO_TRIGGER_SUCCESS = "ANALYSIS_CONTENT_VIDEO_TRIGGER_SUCCESS";
    public const string ANALYSIS_CONTENT_VIDEO_TRIGGER_FAIL = "ANALYSIS_CONTENT_VIDEO_TRIGGER_FAIL";
}