namespace Hhs.TextNormalizerService.Domain.ContentDomain.Consts.Facilities;

public static class ContentNormalizedRequestOperationFacilities
{
    public const string CONTENT_NORMALIZED_REQUEST_CREATED = "CONTENT_NORMALIZED_REQUEST_CREATED";

    public const string CONTENT_NORMALIZED_REQUEST_SCRAPING_SUCCESS = "CONTENT_NORMALIZED_REQUEST_SCRAPING_SUCCESS";
    public const string CONTENT_NORMALIZED_REQUEST_SCRAPING_FAIL = "CONTENT_NORMALIZED_REQUEST_SCRAPING_FAIL";

    public const string CONTENT_NORMALIZED_REQUEST_OUTLINE_SUCCESS = "CONTENT_NORMALIZED_REQUEST_OUTLINE_SUCCESS";
    public const string CONTENT_NORMALIZED_REQUEST_OUTLINE_SKIPPED = "CONTENT_NORMALIZED_REQUEST_OUTLINE_SKIPPED";
    public const string CONTENT_NORMALIZED_REQUEST_OUTLINE_FAIL = "CONTENT_NORMALIZED_REQUEST_OUTLINE_FAIL";

    public const string CONTENT_NORMALIZED_REQUEST_STATUS_FAIL = "CONTENT_NORMALIZED_REQUEST_STATUS_FAIL";

    public const string CUSTOMER_CONTENT_VIDEO_TRIGGER_SUCCESS = "CUSTOMER_CONTENT_VIDEO_TRIGGER_SUCCESS";
    public const string CUSTOMER_CONTENT_VIDEO_TRIGGER_FAIL = "CUSTOMER_CONTENT_VIDEO_TRIGGER_FAIL";
}