<Project Sdk="Microsoft.NET.Sdk">

  <Import Project="..\..\configureawait.props" />
    <Import Project="..\..\common.props" />

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <AssemblyName>HsnSoft.Base.AspNetCore.Serilog</AssemblyName>
        <PackageId>HsnSoft.Base.AspNetCore.Serilog</PackageId>
        <AssetTargetFallback>$(AssetTargetFallback);portable-net45+win8+wp8+wpa81;</AssetTargetFallback>
        <GenerateAssemblyConfigurationAttribute>false</GenerateAssemblyConfigurationAttribute>
        <GenerateAssemblyCompanyAttribute>false</GenerateAssemblyCompanyAttribute>
        <GenerateAssemblyProductAttribute>false</GenerateAssemblyProductAttribute>
        <IsPackable>true</IsPackable>
        <OutputType>Library</OutputType>
        <NoDefaultLaunchSettingsFile>true</NoDefaultLaunchSettingsFile>
        <RootNamespace />
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\HsnSoft.Base.AspNetCore\HsnSoft.Base.AspNetCore.csproj" />
        <ProjectReference Include="..\HsnSoft.Base.MultiTenancy\HsnSoft.Base.MultiTenancy.csproj" />
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Serilog" Version="4.0.1" />
        <PackageReference Include="Serilog.Extensions.Logging" Version="8.0.0" />
        <PackageReference Include="Serilog.Sinks.Async" Version="2.0.0" />
        <PackageReference Include="Serilog.Sinks.File" Version="6.0.0" />
        <PackageReference Include="Serilog.Sinks.Console" Version="6.0.0" />
        <PackageReference Include="Serilog.Sinks.Graylog" Version="3.1.1" />
        <PackageReference Include="Destructurama.Attributed" Version="4.0.0" />
        <PackageReference Include="Destructurama.JsonNet" Version="3.0.0" />
        <PackageReference Include="Serilog.Formatting.Compact" Version="3.0.0" />
    </ItemGroup>

</Project>
