<Project>
    <PropertyGroup>
        <NoWarn>$(NoWarn);CS1591;CS0436</NoWarn>
        <PackageProjectUrl>https://techsummus.com/</PackageProjectUrl>
        <PackageLicenseExpression>LGPL-3.0-only</PackageLicenseExpression>
        <RepositoryType>git</RepositoryType>
        <RepositoryUrl>https://github.com/tech-summus/hhs-shared/</RepositoryUrl>
        <GenerateDocumentationFile>true</GenerateDocumentationFile>
        <!-- Include symbol files (*.pdb) in the built .nupkg -->
        <AllowedOutputExtensionsInPackageBuildOutputFolder>$(AllowedOutputExtensionsInPackageBuildOutputFolder);.pdb</AllowedOutputExtensionsInPackageBuildOutputFolder>
        <GeneratePackageOnBuild>false</GeneratePackageOnBuild>
        <IsPackable>true</IsPackable>
        <OutputType>Library</OutputType>
        <NoDefaultLaunchSettingsFile>true</NoDefaultLaunchSettingsFile>
        <Authors>TechSummus</Authors>
        <Copyright>2025</Copyright>
        <Product>TechSummus HHS Solution</Product>
        <GenerateEmbeddedFilesManifest>true</GenerateEmbeddedFilesManifest>
        <AssetTargetFallback>$(AssetTargetFallback);portable-net45+win8+wp8+wpa81;</AssetTargetFallback>
        <GenerateAssemblyConfigurationAttribute>false</GenerateAssemblyConfigurationAttribute>
        <GenerateAssemblyCompanyAttribute>false</GenerateAssemblyCompanyAttribute>
        <GenerateAssemblyProductAttribute>false</GenerateAssemblyProductAttribute>
    </PropertyGroup>
</Project>
