namespace Hhs.ContentService.Domain.ContentDomain.Consts;

public static class AppContentOperationFacilities
{
    public const string APP_CONTENT_CREATED = "APP_CONTENT_CREATED";
    public const string APP_CONTENT_NORMALIZED_SUCCESS = "APP_CONTENT_NORMALIZED_SUCCESS";
    public const string APP_CONTENT_VIDEO_GENERATION_APPROVED = "APP_CONTENT_VIDEO_GENERATION_APPROVED";

    public const string APP_CONTENT_NORMALIZED_FAIL = "APP_CONTENT_NORMALIZED_FAIL";
    public const string APP_CONTENT_VIDEO_GENERATION_FAIL = "APP_CONTENT_VIDEO_GENERATION_FAIL";
    public const string APP_CONTENT_STATUS_FAIL = "APP_CONTENT_STATUS_FAIL";

    public const string VIDEO_GENERATION_SKIPPED_OLD_CONTENT = "VIDEO_GENERATION_SKIPPED_OLD_CONTENT";
    public const string VIDEO_GENERATION_SKIPPED_EARLY_TIME = "VIDEO_GENERATION_SKIPPED_EARLY_TIME";
    public const string VIDEO_GENERATION_SKIPPED_DAILY_LIMIT = "VIDEO_GENERATION_SKIPPED_DAILY_LIMIT";
    public const string VIDEO_GENERATION_SKIPPED_REGENERATION_FAILED = "VIDEO_GENERATION_SKIPPED_REGENERATION_FAILED";

    public const string APP_CONTENT_VIDEO_GENERATION_SUCCESS = "APP_CONTENT_VIDEO_GENERATION_SUCCESS";

    public const string ADS_STARTED = "STARTED";
    public const string ADS_ERROR = "ERROR";
    public const string ADS_TIMEOUT = "TIMEOUT";
    public const string ADS_EMPTY = "EMPTY";
}