<Project Sdk="Microsoft.NET.Sdk">

    <Import Project="..\..\common.version.props"/>
    <Import Project="..\..\common.test.props"/>
    <Import Project="..\..\common.props"/>

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <PackageId>Hhs.TextNormalizerService.MongoDb</PackageId>
        <RootNamespace>Hhs.TextNormalizerService.MongoDb</RootNamespace>
        <Title>TechSummus Hhs TextNormalizer Service MongoDb</Title>
        <Description>TechSummus Hhs TextNormalizer Service MongoDb</Description>
        <PackageTags>TechSummus Hhs TextNormalizer Service MongoDb</PackageTags>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\..\..\..\src\HsnSoft.Base.MongoDB\HsnSoft.Base.MongoDB.csproj" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\Hhs.TextNormalizerService.Domain\Hhs.TextNormalizerService.Domain.csproj"/>
    </ItemGroup>
</Project>