<Project Sdk="Microsoft.NET.Sdk">

    <Import Project="..\..\common.version.props"/>
    <Import Project="..\..\common.test.props"/>
    <Import Project="..\..\common.props"/>

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <PackageId>Hhs.VideoGeneratorService.MongoDb</PackageId>
        <RootNamespace>Hhs.VideoGeneratorService.MongoDb</RootNamespace>
        <Title>TechSummus Hhs VideoGenerator Service MongoDb</Title>
        <Description>TechSummus Hhs VideoGenerator Service MongoDb</Description>
        <PackageTags>TechSummus Hhs VideoGenerator Service MongoDb</PackageTags>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\Hhs.VideoGeneratorService.Domain\Hhs.VideoGeneratorService.Domain.csproj"/>
    </ItemGroup>
</Project>