namespace HsnSoft.Base.EventBus.Logging;

public enum EventBusLogFacility
{
    PRODUCE_EVENT_ERROR,
    CONSUME_EVENT_HANDLING_ERROR,
    CONSUME_EVENT_HANDLING_STARTED,
    CONSUME_EVENT_HANDLING_FINISHED
}