<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <IsPackable>false</IsPackable>
        <RootNamespace>Hhs.AdministrationService.Test.Shared</RootNamespace>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="FluentAssertions" Version="8.10.0" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\src\Hhs.AdministrationService.Http.Host\Hhs.AdministrationService.Http.Host.csproj"/>
    </ItemGroup>

</Project>
