<Project Sdk="Microsoft.NET.Sdk">

    <Import Project="..\..\common.version.props"/>
    <Import Project="..\..\common.props"/>

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <PackageId>Hhs.Shared.Contracts</PackageId>
        <RootNamespace>Hhs.Shared.Contracts</RootNamespace>
        <Title>TechSummus HHS Shared Contracts</Title>
        <Description>TechSummus HHS Shared Contracts</Description>
        <PackageTags>TechSummus HHS Shared Contracts</PackageTags>
    </PropertyGroup>

    <ItemGroup>
        <!--<PackageReference Include="HsnSoft.Base.Ddd.Application" Version="$(HsnSoftFrameworkVersion)"/>-->
        <!--<PackageReference Include="HsnSoft.Base.EventBus" Version="$(HsnSoftFrameworkVersion)"/>-->
        <ProjectReference Include="..\..\..\..\src\HsnSoft.Base.Ddd.Application\HsnSoft.Base.Ddd.Application.csproj"/>
        <ProjectReference Include="..\..\..\..\src\HsnSoft.Base.EventBus\HsnSoft.Base.EventBus.csproj"/>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\Hhs.Shared.Helper\Hhs.Shared.Helper.csproj"/>
    </ItemGroup>

</Project>