// <auto-generated />
using System;
using Hhs.ContentService.EntityFrameworkCore.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Hhs.ContentService.EntityFrameworkCore.Migrations
{
    [DbContext(typeof(ContentServiceDbContext))]
    partial class ContentServiceDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Hhs.ContentService.Domain.ContentDomain.Entities.AnalysisContent", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("CorrelationId")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("CreationTime");

                    b.Property<Guid?>("CreatorId")
                        .HasColumnType("uuid")
                        .HasColumnName("CreatorId");

                    b.Property<string>("DomainName")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("FinalVideoUrl")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("IsDeleted");

                    b.Property<string>("LastError")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("LastFacility")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<DateTime>("LastModificationTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("LastModificationTime");

                    b.Property<Guid?>("LastModifierId")
                        .HasColumnType("uuid")
                        .HasColumnName("LastModifierId");

                    b.Property<Guid?>("NormalizeRequestId")
                        .HasColumnType("uuid");

                    b.Property<string>("NormalizeStatus")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<string>("ScopeKey")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Title")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<Guid?>("VideoRequestId")
                        .HasColumnType("uuid");

                    b.Property<string>("VideoStatus")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.HasKey("Id");

                    b.HasIndex("ScopeKey");

                    b.ToTable("AnalysisContents", (string)null);
                });

            modelBuilder.Entity("Hhs.ContentService.Domain.ContentDomain.Entities.AnalysisContentItem", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("AnalysisContentId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CustomerContentId")
                        .HasColumnType("uuid");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CustomerContentId");

                    b.HasIndex("AnalysisContentId", "CustomerContentId")
                        .IsUnique();

                    b.HasIndex("AnalysisContentId", "SortOrder")
                        .IsUnique();

                    b.ToTable("AnalysisContentItems", (string)null);
                });

            modelBuilder.Entity("Hhs.ContentService.Domain.ContentDomain.Entities.CustomerContent", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("AudioRequestId")
                        .HasColumnType("uuid");

                    b.Property<string>("ContentKey")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("CorrelationId")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("CreationTime");

                    b.Property<Guid?>("CreatorId")
                        .HasColumnType("uuid")
                        .HasColumnName("CreatorId");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("IsDeleted");

                    b.Property<string>("LastError")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("LastFacility")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<DateTime>("LastModificationTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("LastModificationTime");

                    b.Property<Guid?>("LastModifierId")
                        .HasColumnType("uuid")
                        .HasColumnName("LastModifierId");

                    b.Property<Guid?>("NormalizeRequestId")
                        .HasColumnType("uuid");

                    b.Property<string>("NormalizeStatus")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<string>("ScopeKey")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime?>("ScrapReleaseTimeUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("SlugKey")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("VideoCdnUrl")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<Guid?>("VideoRequestId")
                        .HasColumnType("uuid");

                    b.Property<string>("VideoStatus")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.HasKey("Id");

                    b.HasIndex("ScopeKey");

                    b.HasIndex("ScopeKey", "ContentKey")
                        .IsUnique();

                    b.ToTable("CustomerContents", (string)null);
                });

            modelBuilder.Entity("Hhs.ContentService.Domain.InfraDomain.Entities.EventInboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("CorrelationId")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("CreationTime");

                    b.Property<Guid?>("CreatorId")
                        .HasColumnType("uuid")
                        .HasColumnName("CreatorId");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("EventName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<DateTime>("LastModificationTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("LastModificationTime");

                    b.Property<Guid?>("LastModifierId")
                        .HasColumnType("uuid")
                        .HasColumnName("LastModifierId");

                    b.Property<string>("Payload")
                        .HasColumnType("jsonb");

                    b.Property<DateTime?>("ProcessedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("RetryCount")
                        .HasColumnType("integer");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("Status");

                    b.ToTable("EventInboxMessages", (string)null);
                });

            modelBuilder.Entity("Hhs.ContentService.Domain.SettingDomain.Entities.ContentVideoGenerationLimit", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("ContentReferenceIds")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<Guid?>("CustomerVpSettingId")
                        .HasColumnType("uuid");

                    b.Property<string>("ScopeKey")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<DateTime>("VideoGenerationDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("VideoGenerationType")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CustomerVpSettingId");

                    b.HasIndex("ScopeKey", "VideoGenerationType");

                    b.ToTable("ContentVideoGenerationLimits", (string)null);
                });

            modelBuilder.Entity("Hhs.ContentService.Domain.SettingDomain.Entities.CustomerVpSetting", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("CreationTime");

                    b.Property<Guid?>("CreatorId")
                        .HasColumnType("uuid")
                        .HasColumnName("CreatorId");

                    b.Property<int>("DailyAnalysisVideoGenerationLimit")
                        .HasColumnType("integer");

                    b.Property<int>("DailyAnalysisVideoGenerationStartedUtcHour")
                        .HasColumnType("integer");

                    b.Property<int>("DailyDirectVideoGenerationLimit")
                        .HasColumnType("integer");

                    b.Property<int>("DailyDirectVideoGenerationStartedUtcHour")
                        .HasColumnType("integer");

                    b.Property<int>("DailyTrendVideoGenerationLimit")
                        .HasColumnType("integer");

                    b.Property<int>("DailyTrendVideoGenerationStartedUtcHour")
                        .HasColumnType("integer");

                    b.Property<int>("DailyTrendVideoMinVisitCount")
                        .HasColumnType("integer");

                    b.Property<int>("DailyTrendVideoWaitStatisticHour")
                        .HasColumnType("integer");

                    b.Property<string>("DomainName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("ExcludePathFilters")
                        .HasColumnType("jsonb");

                    b.Property<string>("IncludePathFilters")
                        .HasColumnType("jsonb");

                    b.Property<bool>("IsBlocked")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("IsDeleted");

                    b.Property<DateTime>("LastModificationTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("LastModificationTime");

                    b.Property<Guid?>("LastModifierId")
                        .HasColumnType("uuid")
                        .HasColumnName("LastModifierId");

                    b.Property<string>("ScopeKey")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.HasKey("Id");

                    b.HasIndex("DomainName")
                        .IsUnique();

                    b.HasIndex("ScopeKey")
                        .IsUnique();

                    b.ToTable("CustomerVpSettings", (string)null);
                });

            modelBuilder.Entity("Hhs.ContentService.Domain.ContentDomain.Entities.AnalysisContentItem", b =>
                {
                    b.HasOne("Hhs.ContentService.Domain.ContentDomain.Entities.AnalysisContent", "AnalysisContent")
                        .WithMany("Items")
                        .HasForeignKey("AnalysisContentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Hhs.ContentService.Domain.ContentDomain.Entities.CustomerContent", "CustomerContent")
                        .WithMany()
                        .HasForeignKey("CustomerContentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AnalysisContent");

                    b.Navigation("CustomerContent");
                });

            modelBuilder.Entity("Hhs.ContentService.Domain.SettingDomain.Entities.ContentVideoGenerationLimit", b =>
                {
                    b.HasOne("Hhs.ContentService.Domain.SettingDomain.Entities.CustomerVpSetting", null)
                        .WithMany("VideoGenerationHistories")
                        .HasForeignKey("CustomerVpSettingId");
                });

            modelBuilder.Entity("Hhs.ContentService.Domain.ContentDomain.Entities.AnalysisContent", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("Hhs.ContentService.Domain.SettingDomain.Entities.CustomerVpSetting", b =>
                {
                    b.Navigation("VideoGenerationHistories");
                });
#pragma warning restore 612, 618
        }
    }
}
