<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <IsPackable>false</IsPackable>
        <RootNamespace>HsnSoft.Base.Test.Api.Helper</RootNamespace>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\src\HsnSoft.Base.Core\HsnSoft.Base.Core.csproj" />
    </ItemGroup>

</Project>
