namespace Hhs.TextNormalizerService.Domain.ContentDomain.Consts;

public static class NormalizedRequestOperationFacilities
{
    public const string NORMALIZED_REQUEST_CREATED = "NORMALIZED_REQUEST_CREATED";
    public const string NORMALIZED_REQUEST_SCRAPING_SUCCESS = "CONTENT_SCRAPING_SUCCESS";
    public const string NORMALIZED_REQUEST_SCRAPING_FAIL = "CONTENT_SCRAPING_FAIL";
    public const string NORMALIZED_REQUEST_OUTLINE_SUCCESS = "CONTENT_OUTLINE_SUCCESS";
    public const string NORMALIZED_REQUEST_OUTLINE_SKIPPED = "CONTENT_OUTLINE_SKIPPED";
    public const string NORMALIZED_REQUEST_OUTLINE_FAIL = "CONTENT_OUTLINE_FAIL";

    public const string NORMALIZED_REQUEST_STATUS_FAIL = "NORMALIZED_REQUEST_STATUS_FAIL";

    public const string VIDEO_CREATION_TRIGGER_SUCCESS = "VIDEO_CREATION_TRIGGER_SUCCESS";
    public const string VIDEO_CREATION_TRIGGER_FAIL = "VIDEO_CREATION_TRIGGER_FAIL";
}