namespace Hhs.VideoGeneratorService.Domain.VideoDomain.Consts;

public static class VideoRequestOperationFacilities
{
    public const string VIDEO_REQUEST_CREATED = "VIDEO_REQUEST_CREATED";
    public const string VIDEO_REQUEST_SEND_SUCCESS = "VIDEO_REQUEST_SEND_SUCCESS";
    public const string VIDEO_REQUEST_SEND_FAIL = "VIDEO_REQUEST_SEND_FAIL";
    public const string AUDIO_REQUEST_CREATED = "AUDIO_REQUEST_CREATED";
    public const string AUDIO_REQUEST_SEND_SUCCESS = "AUDIO_REQUEST_SEND_SUCCESS";
    public const string AUDIO_REQUEST_SEND_FAIL = "AUDIO_REQUEST_SEND_FAIL";
    public const string AUDIO_REQUEST_IS_GENERATING = "AUDIO_REQUEST_IS_GENERATING";
    public const string AUDIO_FILE_STORAGE_UPLOAD_SUCCESS = "AUDIO_FILE_STORAGE_UPLOAD_SUCCESS";
    public const string AUDIO_FILE_STORAGE_UPLOAD_FAIL = "AUDIO_FILE_STORAGE_UPLOAD_FAIL";
    public const string VIDEO_REQUEST_IS_GENERATING = "VIDEO_REQUEST_IS_GENERATING";
    public const string VIDEO_REQUEST_QUERY_GENERATION_SUCCESS = "VIDEO_REQUEST_QUERY_GENERATION_SUCCESS";
    public const string VIDEO_REQUEST_QUERY_GENERATION_FAIL = "VIDEO_REQUEST_QUERY_GENERATION_FAIL";
    public const string VIDEO_FILE_DOWNLOAD_SUCCESS = "VIDEO_FILE_DOWNLOAD_SUCCESS";
    public const string VIDEO_FILE_DOWNLOAD_FAIL = "VIDEO_FILE_DOWNLOAD_FAIL";
    public const string VIDEO_FILE_STORAGE_UPLOAD_SUCCESS = "VIDEO_FILE_STORAGE_UPLOAD_SUCCESS";
    public const string VIDEO_FILE_STORAGE_UPLOAD_FAIL = "VIDEO_FILE_STORAGE_UPLOAD_FAIL";
    public const string VIDEO_REQUEST_STATUS_FAIL = "VIDEO_REQUEST_STATUS_FAIL";
}