<Project Sdk="Microsoft.NET.Sdk">

    <Import Project="..\..\configureawait.props" />
    <Import Project="..\..\common.props" />

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <AssemblyName>HsnSoft.Base.Http.Client</AssemblyName>
        <PackageId>HsnSoft.Base.Http.Client</PackageId>
        <AssetTargetFallback>$(AssetTargetFallback);portable-net45+win8+wp8+wpa81;</AssetTargetFallback>
        <GenerateAssemblyConfigurationAttribute>false</GenerateAssemblyConfigurationAttribute>
        <GenerateAssemblyCompanyAttribute>false</GenerateAssemblyCompanyAttribute>
        <GenerateAssemblyProductAttribute>false</GenerateAssemblyProductAttribute>
        <RootNamespace />
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="IdentityModel" Version="7.0.0" />
        <PackageReference Include="Microsoft.Extensions.Http" Version="$(MicrosoftPackageVersion)" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\HsnSoft.Base.AspNetCore.Mvc\HsnSoft.Base.AspNetCore.Mvc.csproj" />
        <ProjectReference Include="..\HsnSoft.Base.ExceptionHandling\HsnSoft.Base.ExceptionHandling.csproj" />
        <ProjectReference Include="..\HsnSoft.Base.MultiTenancy\HsnSoft.Base.MultiTenancy.csproj" />
        <ProjectReference Include="..\HsnSoft.Base.Validation\HsnSoft.Base.Validation.csproj" />
    </ItemGroup>

</Project>
