<Project Sdk="Microsoft.NET.Sdk">

    <Import Project="..\..\common.version.props"/>
    <Import Project="..\..\common.props"/>

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <PackageId>Hhs.Shared.Hosting</PackageId>
        <RootNamespace>Hhs.Shared.Hosting</RootNamespace>
        <Title>TechSummus HHS Shared Hosting</Title>
        <Description>TechSummus HHS Shared Hosting</Description>
        <PackageTags>TechSummus HHS Shared Hosting</PackageTags>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="AspNetCore.HealthChecks.Uris" Version="9.0.0"/>
        <PackageReference Include="AspNetCore.HealthChecks.UI.Client" Version="9.0.0"/>
        <PackageReference Include="AspNetCore.HealthChecks.MongoDb" Version="9.0.0"/>
        <PackageReference Include="AspNetCore.HealthChecks.NpgSql" Version="9.0.0"/>
        <PackageReference Include="UAParser" Version="3.1.47"/>
    </ItemGroup>

    <ItemGroup>
<!--        <PackageReference Include="HsnSoft.Base.AspNetCore.Mvc" Version="$(HsnSoftFrameworkVersion)"/>-->
<!--        <PackageReference Include="HsnSoft.Base.Swashbuckle" Version="$(HsnSoftFrameworkVersion)"/>-->
<!--        <PackageReference Include="HsnSoft.Base.EventBus.RabbitMQ" Version="$(HsnSoftFrameworkVersion)"/>-->
<!--        <PackageReference Include="HsnSoft.Base.Caching.StackExchangeRedis" Version="$(HsnSoftFrameworkVersion)"/>-->
        <ProjectReference Include="..\..\..\..\src\HsnSoft.Base.AspNetCore.Mvc\HsnSoft.Base.AspNetCore.Mvc.csproj" />
        <ProjectReference Include="..\..\..\..\src\HsnSoft.Base.Caching.StackExchangeRedis\HsnSoft.Base.Caching.StackExchangeRedis.csproj" />
        <ProjectReference Include="..\..\..\..\src\HsnSoft.Base.EventBus.RabbitMQ\HsnSoft.Base.EventBus.RabbitMQ.csproj" />
        <ProjectReference Include="..\..\..\..\src\HsnSoft.Base.Swashbuckle\HsnSoft.Base.Swashbuckle.csproj" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\Hhs.Shared.Helper\Hhs.Shared.Helper.csproj"/>
    </ItemGroup>

</Project>