<Project Sdk="Microsoft.NET.Sdk">

    <Import Project="..\..\common.version.props"/>
    <Import Project="..\..\common.props"/>

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <PackageId>Hhs.Shared.Helper</PackageId>
        <RootNamespace>Hhs.Shared.Helper</RootNamespace>
        <Title>TechSummus HHS Shared Helper</Title>
        <Description>TechSummus HHS Shared Helper</Description>
        <PackageTags>TechSummus HHS Shared Helper</PackageTags>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="MailKit" Version="4.17.0" />
        <PackageReference Include="MimeKit" Version="4.17.0" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\..\..\src\HsnSoft.Base.Ddd.Domain\HsnSoft.Base.Ddd.Domain.csproj" />
    </ItemGroup>
    
    <ItemGroup>
        <ProjectReference Include="..\Hhs.Shared.Localization\Hhs.Shared.Localization.csproj"/>
    </ItemGroup>

</Project>