<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <IsPackable>false</IsPackable>
        <RootNamespace>HsnSoft.Base.Test.Api.Hosting</RootNamespace>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Swashbuckle.AspNetCore" Version="10.1.4" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\src\HsnSoft.Base.AspNetCore.Serilog\HsnSoft.Base.AspNetCore.Serilog.csproj" />
        <ProjectReference Include="..\HsnSoft.Base.Test.Api.Helper\HsnSoft.Base.Test.Api.Helper.csproj" />
    </ItemGroup>

</Project>
