<Project Sdk="Microsoft.NET.Sdk">

    <Import Project="..\..\common.version.props"/>
    <Import Project="..\..\common.test.props"/>
    <Import Project="..\..\common.props"/>

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <PackageId>Hhs.EventManagerService.MongoDb</PackageId>
        <RootNamespace>Hhs.EventManagerService.MongoDb</RootNamespace>
        <Title>TechSummus Hhs EventManager Service MongoDb</Title>
        <Description>TechSummus Hhs EventManager Service MongoDb</Description>
        <PackageTags>TechSummus Hhs EventManager Service MongoDb</PackageTags>
    </PropertyGroup>
    
    <ItemGroup>
        <ProjectReference Include="..\Hhs.EventManagerService.Domain\Hhs.EventManagerService.Domain.csproj"/>
    </ItemGroup>
</Project>