<Project Sdk="Microsoft.NET.Sdk">

    <Import Project="..\..\common.version.props"/>
    <Import Project="..\..\common.test.props"/>
    <Import Project="..\..\common.props"/>

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <PackageId>Hhs.VideoGeneratorService.Application</PackageId>
        <RootNamespace>Hhs.VideoGeneratorService.Application</RootNamespace>
        <Title>TechSummus Hhs VideoGenerator Service Application</Title>
        <Description>TechSummus Hhs VideoGenerator Service Application</Description>
        <PackageTags>TechSummus Hhs VideoGenerator Service Application</PackageTags>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\..\..\..\src\HsnSoft.Base.BlobStoring.Aws\HsnSoft.Base.BlobStoring.Aws.csproj" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\..\..\shared\src\Hhs.Shared.Contracts\Hhs.Shared.Contracts.csproj" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\Hhs.VideoGeneratorService.Domain\Hhs.VideoGeneratorService.Domain.csproj"/>
    </ItemGroup>

</Project>