// <auto-generated />
using System;
using Hhs.ContentService.EntityFrameworkCore.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Hhs.ContentService.EntityFrameworkCore.Migrations
{
    [DbContext(typeof(ContentServiceDbContext))]
    [Migration("20260529151419_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Hhs.ContentService.Domain.ClientDomain.Entities.Client", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("CreationTime");

                    b.Property<Guid?>("CreatorId")
                        .HasColumnType("uuid")
                        .HasColumnName("CreatorId");

                    b.Property<int>("DailyAnalysisVideoGenerationLimit")
                        .HasColumnType("integer");

                    b.Property<int>("DailyAnalysisVideoGenerationStartedUtcHour")
                        .HasColumnType("integer");

                    b.Property<int>("DailyDirectVideoGenerationLimit")
                        .HasColumnType("integer");

                    b.Property<int>("DailyDirectVideoGenerationStartedUtcHour")
                        .HasColumnType("integer");

                    b.Property<int>("DailyTrendVideoGenerationLimit")
                        .HasColumnType("integer");

                    b.Property<int>("DailyTrendVideoGenerationStartedUtcHour")
                        .HasColumnType("integer");

                    b.Property<int>("DailyTrendVideoMinVisitCount")
                        .HasColumnType("integer");

                    b.Property<int>("DailyTrendVideoWaitStatisticHour")
                        .HasColumnType("integer");

                    b.Property<string>("DomainName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("IsBlocked")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("IsDeleted");

                    b.Property<DateTime>("LastModificationTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("LastModificationTime");

                    b.Property<Guid?>("LastModifierId")
                        .HasColumnType("uuid")
                        .HasColumnName("LastModifierId");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("TenantId");

                    b.HasKey("Id");

                    b.HasIndex("IsDeleted");

                    b.HasIndex("TenantId", "DomainName")
                        .IsUnique();

                    b.ToTable("Clients", (string)null);
                });

            modelBuilder.Entity("Hhs.ContentService.Domain.ClientDomain.Entities.ClientPathFilter", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<int>("ClientFilterType")
                        .HasColumnType("integer");

                    b.Property<Guid>("ClientId")
                        .HasColumnType("uuid");

                    b.Property<string>("PathFilterName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.ToTable("ClientPathFilters", (string)null);
                });

            modelBuilder.Entity("Hhs.ContentService.Domain.ClientDomain.Entities.ClientVideoGenerationHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ClientId")
                        .HasColumnType("uuid");

                    b.Property<string>("ContentReferenceIds")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<DateTime>("VideoGenerationDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("VideoGenerationType")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ClientId", "VideoGenerationType");

                    b.ToTable("ClientVideoGenerationHistories", (string)null);
                });

            modelBuilder.Entity("Hhs.ContentService.Domain.ContentDomain.Entities.AnalysisContent", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("AnalysisDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("AnalysisDate");

                    b.Property<Guid>("ClientId")
                        .HasColumnType("uuid")
                        .HasColumnName("ClientId");

                    b.Property<string>("CorrelationId")
                        .HasColumnType("text")
                        .HasColumnName("CorrelationId");

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("CreationTime");

                    b.Property<Guid?>("CreatorId")
                        .HasColumnType("uuid")
                        .HasColumnName("CreatorId");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("IsDeleted");

                    b.Property<DateTime>("LastModificationTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("LastModificationTime");

                    b.Property<Guid?>("LastModifierId")
                        .HasColumnType("uuid")
                        .HasColumnName("LastModifierId");

                    b.Property<Guid?>("NormalizedAnalysisId")
                        .HasColumnType("uuid")
                        .HasColumnName("NormalizedAnalysisId");

                    b.Property<int>("OperationStatus")
                        .HasColumnType("integer")
                        .HasColumnName("OperationStatus");

                    b.Property<string>("OperationStatusDescription")
                        .HasColumnType("text")
                        .HasColumnName("OperationStatusDescription");

                    b.Property<string>("StorageVideoUrl")
                        .HasColumnType("text")
                        .HasColumnName("StorageVideoUrl");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("TenantId");

                    b.Property<Guid?>("VideoRequestId")
                        .HasColumnType("uuid")
                        .HasColumnName("VideoRequestId");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.HasIndex("IsDeleted");

                    b.HasIndex("OperationStatus");

                    b.HasIndex("TenantId");

                    b.ToTable("AnalysisContents", (string)null);
                });

            modelBuilder.Entity("Hhs.ContentService.Domain.ContentDomain.Entities.AppContent", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ClientId")
                        .HasColumnType("uuid")
                        .HasColumnName("ClientId");

                    b.Property<string>("CorrelationId")
                        .HasColumnType("text")
                        .HasColumnName("CorrelationId");

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("CreationTime");

                    b.Property<Guid?>("CreatorId")
                        .HasColumnType("uuid")
                        .HasColumnName("CreatorId");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("IsDeleted");

                    b.Property<DateTime>("LastModificationTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("LastModificationTime");

                    b.Property<Guid?>("LastModifierId")
                        .HasColumnType("uuid")
                        .HasColumnName("LastModifierId");

                    b.Property<Guid?>("NormalizedRequestId")
                        .HasColumnType("uuid")
                        .HasColumnName("NormalizedRequestId");

                    b.Property<int>("OperationStatus")
                        .HasColumnType("integer")
                        .HasColumnName("OperationStatus");

                    b.Property<string>("OperationStatusDescription")
                        .HasColumnType("text")
                        .HasColumnName("OperationStatusDescription");

                    b.Property<DateTime?>("ReleaseTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ReleaseTime");

                    b.Property<string>("SlugKey")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("SlugKey");

                    b.Property<string>("StorageVideoUrl")
                        .HasColumnType("text")
                        .HasColumnName("StorageVideoUrl");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("TenantId");

                    b.Property<Guid?>("VideoRequestId")
                        .HasColumnType("uuid")
                        .HasColumnName("VideoRequestId");

                    b.HasKey("Id");

                    b.HasIndex("IsDeleted");

                    b.HasIndex("OperationStatus");

                    b.HasIndex("TenantId");

                    b.HasIndex("ClientId", "SlugKey");

                    b.ToTable("AppContents", (string)null);
                });

            modelBuilder.Entity("Hhs.ContentService.Domain.ContentDomain.Entities.AppContentVisit", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("AppContentId")
                        .HasColumnType("uuid")
                        .HasColumnName("AppContentId");

                    b.Property<Guid>("ClientId")
                        .HasColumnType("uuid")
                        .HasColumnName("ClientId");

                    b.Property<string>("VisitResponse")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("VisitResponse");

                    b.Property<long>("VisitTimeLine")
                        .HasColumnType("bigint")
                        .HasColumnName("VisitTimeLine");

                    b.HasKey("Id");

                    b.HasIndex("ClientId", "AppContentId");

                    b.HasIndex("ClientId", "VisitResponse");

                    b.HasIndex("ClientId", "VisitTimeLine");

                    b.ToTable("AppContentVisits", (string)null);
                });

            modelBuilder.Entity("Hhs.ContentService.Domain.DashboardDomain.Entities.ResponseStatistic", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ClientId")
                        .HasColumnType("uuid")
                        .HasColumnName("ClientId");

                    b.Property<decimal>("ResponseCount")
                        .HasColumnType("numeric(20,0)")
                        .HasColumnName("ResponseCount");

                    b.Property<string>("ResponseStatus")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("ResponseStatus");

                    b.Property<decimal>("ResponseTime")
                        .HasColumnType("numeric(20,0)")
                        .HasColumnName("ResponseTime");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("TenantId");

                    b.HasKey("Id");

                    b.HasIndex("TenantId");

                    b.HasIndex("ClientId", "ResponseStatus");

                    b.HasIndex("ClientId", "ResponseTime");

                    b.ToTable("ResponseStatistics", (string)null);
                });

            modelBuilder.Entity("Hhs.ContentService.Domain.ClientDomain.Entities.ClientPathFilter", b =>
                {
                    b.HasOne("Hhs.ContentService.Domain.ClientDomain.Entities.Client", "Client")
                        .WithMany("PathFilters")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Client");
                });

            modelBuilder.Entity("Hhs.ContentService.Domain.ClientDomain.Entities.ClientVideoGenerationHistory", b =>
                {
                    b.HasOne("Hhs.ContentService.Domain.ClientDomain.Entities.Client", "Client")
                        .WithMany("VideoGenerationHistories")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Client");
                });

            modelBuilder.Entity("Hhs.ContentService.Domain.ContentDomain.Entities.AnalysisContent", b =>
                {
                    b.HasOne("Hhs.ContentService.Domain.ClientDomain.Entities.Client", "Client")
                        .WithMany()
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Client");
                });

            modelBuilder.Entity("Hhs.ContentService.Domain.ContentDomain.Entities.AppContent", b =>
                {
                    b.HasOne("Hhs.ContentService.Domain.ClientDomain.Entities.Client", "Client")
                        .WithMany()
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Client");
                });

            modelBuilder.Entity("Hhs.ContentService.Domain.ClientDomain.Entities.Client", b =>
                {
                    b.Navigation("PathFilters");

                    b.Navigation("VideoGenerationHistories");
                });
#pragma warning restore 612, 618
        }
    }
}
