name: .NETCore
on:
  workflow_dispatch:
  push:
    branches: [ "feat/*" ]
  pull_request:
    branches: [ "dev","rel/*" ]
    types: [opened, synchronize, reopened]

jobs:
  build:
    name: Build And Test JOB
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 6.0.x
          
      - name: Restore dependencies
        run: dotnet restore --force --no-cache --verbosity normal
        
      - name: Build
        run: dotnet build --no-restore --no-incremental --verbosity normal
        
      - name: Test
        run: dotnet test --no-restore --no-build --verbosity normal
